# Generated by Django 4.1.5 on 2023-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('salary', models.FloatField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
